In [1]:
out = []

s = "x"

out.append(s)
out

['x']

In [2]:
out.append("e")
out

['x', 'e']

In [3]:
''.join(out)

'xe'

In [4]:
import torch

In [5]:
W = torch.randn((27, 1))
W

tensor([[ 0.0147],
        [-0.9614],
        [-0.6302],
        [ 0.3817],
        [-1.3300],
        [ 1.3339],
        [-1.8496],
        [ 0.4199],
        [-0.1827],
        [-0.3539],
        [-0.7269],
        [-0.7979],
        [ 0.6924],
        [-0.3591],
        [ 0.9909],
        [-0.2298],
        [-0.2234],
        [-0.5300],
        [-1.1996],
        [-0.8522],
        [-0.4534],
        [-0.6875],
        [-0.7985],
        [ 0.2492],
        [ 2.7229],
        [-0.4984],
        [-0.8601]])

In [6]:
# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('shake.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [7]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(' '.join(chars))
print(vocab_size)


   ! $ & ' , - . 3 : ; ? A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z
65


### Tokenizer

In [8]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

In [9]:
stoi

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [10]:
itos

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [11]:
encode('Abracadabra')

[13, 40, 56, 39, 41, 39, 42, 39, 40, 56, 39]

In [12]:
decode(encode('Abracadabra'))

'Abracadabra'

In [13]:
import torch

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
data[:100]

torch.Size([1115394]) torch.int64


tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])

In [14]:
# Train and test splits
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [15]:
context_length = 8

train_data[:context_length+1]  # when you sample a chunk of data like this,
train_data

tensor([18, 47, 56,  ..., 43, 56, 43])

In [16]:
x = train_data[:context_length]
y = train_data[1:context_length+1]
for t in range(context_length):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context}, the target: {target}")

when input is tensor([18]), the target: 47
when input is tensor([18, 47]), the target: 56
when input is tensor([18, 47, 56]), the target: 57
when input is tensor([18, 47, 56, 57]), the target: 58
when input is tensor([18, 47, 56, 57, 58]), the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]), the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]), the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]), the target: 58


In [17]:
print(x)
print(y)

tensor([18, 47, 56, 57, 58,  1, 15, 47])
tensor([47, 56, 57, 58,  1, 15, 47, 58])


In [18]:
torch.manual_seed(42)

batch_size = 4 # how many independent sequences will we process in parallel?
context_length = 8 # maximum context for predictions

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - context_length, (batch_size,))  # random offsets
    print(f'index: {ix}')
    x = torch.stack([data[i:i+context_length] for i in ix])
    y = torch.stack([data[i+1:i+context_length+1] for i in ix])
    x, y = x, y
    return x, y


xb, yb = get_batch('train')
print('inputs: ')
print(xb.shape)
print(xb)
print('targets: ')
print(yb.shape)
print(yb)

print('------')

for b in range(batch_size):             # batch dimension
    for t in range(context_length):     # time dimension
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"when input is {context.tolist()} the target: {target}")

index: tensor([476250,  18899, 645194, 831150])
inputs: 
torch.Size([4, 8])
tensor([[57,  1, 46, 47, 57,  1, 50, 53],
        [ 1, 58, 46, 43, 56, 43,  1, 41],
        [17, 26, 15, 17, 10,  0, 32, 53],
        [57, 58,  6,  1, 61, 47, 58, 46]])
targets: 
torch.Size([4, 8])
tensor([[ 1, 46, 47, 57,  1, 50, 53, 60],
        [58, 46, 43, 56, 43,  1, 41, 39],
        [26, 15, 17, 10,  0, 32, 53,  1],
        [58,  6,  1, 61, 47, 58, 46,  0]])
------
when input is [57] the target: 1
when input is [57, 1] the target: 46
when input is [57, 1, 46] the target: 47
when input is [57, 1, 46, 47] the target: 57
when input is [57, 1, 46, 47, 57] the target: 1
when input is [57, 1, 46, 47, 57, 1] the target: 50
when input is [57, 1, 46, 47, 57, 1, 50] the target: 53
when input is [57, 1, 46, 47, 57, 1, 50, 53] the target: 60
when input is [1] the target: 58
when input is [1, 58] the target: 46
when input is [1, 58, 46] the target: 43
when input is [1, 58, 46, 43] the target: 56
when input is [1, 58, 

In [19]:
# our input in the transformer
xb

tensor([[57,  1, 46, 47, 57,  1, 50, 53],
        [ 1, 58, 46, 43, 56, 43,  1, 41],
        [17, 26, 15, 17, 10,  0, 32, 53],
        [57, 58,  6,  1, 61, 47, 58, 46]])

### Simplest model

In [20]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(42)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('shake.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)  #
print(' '.join(chars))
print(vocab_size)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()

        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    
    def forward(self, idx, targets):

        # idx and targets are both (B, T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)  # logits are basically the scores for the next character in the sequence
        # predicting what comes next based on just the individual identity of a single token, currently the tokens are not talking to each other
        return logits


   ! $ & ' , - . 3 : ; ? A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z
65


In [21]:
m = BigramLanguageModel(vocab_size)
m

BigramLanguageModel(
  (token_embedding_table): Embedding(65, 65)
)

In [22]:
out = m(xb, yb)
print(out.shape)
out

torch.Size([4, 8, 65])


tensor([[[ 0.4224, -0.8596,  0.2910,  ...,  0.2380, -0.1270,  0.0534],
         [ 0.8564,  2.2181,  0.5232,  ...,  0.4114,  1.9312,  1.0119],
         [ 0.4851,  0.0060,  1.0007,  ..., -0.0776, -0.5015, -2.2270],
         ...,
         [ 0.8564,  2.2181,  0.5232,  ...,  0.4114,  1.9312,  1.0119],
         [-0.3991, -0.5458, -0.9493,  ...,  0.0233, -1.0358,  0.6917],
         [ 1.9442,  1.1369, -0.9768,  ...,  0.4025,  1.5574,  2.0379]],

        [[ 0.8564,  2.2181,  0.5232,  ...,  0.4114,  1.9312,  1.0119],
         [ 1.0923, -1.3024,  1.3521,  ..., -0.2658, -1.4075, -0.7460],
         [ 0.4851,  0.0060,  1.0007,  ..., -0.0776, -0.5015, -2.2270],
         ...,
         [ 0.0210, -0.0545, -0.8116,  ...,  1.2781,  0.3526, -0.0750],
         [ 0.8564,  2.2181,  0.5232,  ...,  0.4114,  1.9312,  1.0119],
         [ 0.2751,  0.4683, -0.7030,  ...,  0.1575, -1.1567,  1.8156]],

        [[ 1.3978, -0.9167, -0.7794,  ..., -0.5841,  0.1061, -0.3067],
         [ 1.5735,  1.8697, -1.0639,  ...,  1

In [24]:
class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()

        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    
    def forward(self, idx, targets):

        # idx and targets are both (B, T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)  # logits are basically the scores for the next character in the sequence
        
        loss = F.cross_entropy(logits, targets) # measures quality of the logits with respect to the targets; we have the identity of the next char, how well we are predicting the next char

        return logits

In [25]:
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)

RuntimeError: Expected target size [4, 65], got [4, 8]

In [29]:
# crossentropy wants a B, C, T

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()

        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    
    def forward(self, idx, targets):

        # idx and targets are both (B, T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)  # logits are basically the scores for the next character in the sequence
        print(f"logits shape before reshaping: {logits.shape}")

        # reshape the logits
        B, T, C = logits.shape
        logits = logits.view(B*T, C) # from 3D to 2D to conform to the cross_entropy expected dims
        print(f"logits shape after reshaping: {logits.shape}")

        # reshape the targets
        print(f"targets shape before reshaping: {targets.shape}")
        targets = targets.view(B*T)
        print(f"targets shape after reshaping: {targets.shape}")
        
        loss = F.cross_entropy(logits, targets) # measures quality of the logits with respect to the targets; we have the identity of the next char, how well we are predicting the next char

        return logits, loss

In [32]:
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(f'loss: {loss}')

logits shape before reshaping: torch.Size([4, 8, 65])
logits shape after reshaping: torch.Size([32, 65])
targets shape before reshaping: torch.Size([4, 8])
targets shape after reshaping: torch.Size([32])
loss: 4.5403618812561035


In [ ]:
# we are expecting loss to be ln(1/65) = 4.174387
# our loss telling us that the initial predictions are not super diffuse, it got a little bit of entropy and
# we're guessing wrong

In [47]:
# now to inference

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()

        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    
    def forward(self, idx, targets=None):

        # idx and targets are both (B, T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)  # logits are basically the scores for the next character in the sequence

        if targets is None:
            loss = None
        
        else:
            # reshape the logits
            B, T, C = logits.shape
            logits = logits.view(B*T, C) # from 3D to 2D to conform to the cross_entropy expected dims

            # reshape the targets
            targets = targets.view(B*T)
            
            loss = F.cross_entropy(logits, targets) # measures quality of the logits with respect to the targets; we have the identity of the next char, how well we are predicting the next char

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B,T) array of indices in the current context

        for _ in range(max_new_tokens):

            # get the predictions
            logits, loss = self(idx)
            #print(self(idx))
            #print(f"logits shape: {logits}")
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B,C), getting the last element of the Time dimension
            #print(f"logits reshape: {logits}")
            # aply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B,C)

            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)

            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
            #print(f"idx catted: {idx}")
        
        return idx


In [48]:
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(f'loss: {loss}')

loss: 4.843300819396973


In [49]:
# currently we are feeding in the whole ammount of characters to predict the next char given a current one, but we'll see next why
# the output is garbage, because the model is untrained.

idxs = torch.zeros((1, 1), dtype=torch.long) # kickoff the generation, using 0's as the starting point for generation
decode(m.generate(idxs, max_new_tokens=100)[0].tolist())

'\nmGEE\nNa,K-OmZLpwYw-tJZ.\n;H,!axi.sZRBHYMS&T,H,XiiRVFNPx;YVgB3,Jzu&TZl!M;nXnhCtzduoG&pCFPXwzqi.dgwCiJS'

### Training

In [53]:
m.parameters

<bound method Module.parameters of BigramLanguageModel(
  (token_embedding_table): Embedding(65, 65)
)>

In [50]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [54]:
# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - context_length, (batch_size,))  # random offsets

    x = torch.stack([data[i:i+context_length] for i in ix])
    y = torch.stack([data[i+1:i+context_length+1] for i in ix])
    x, y = x, y
    
    return x, y

In [56]:
batch_size = 32
for steps in range(100):

    # sample a batch of data
    xb, yb = get_batch('train')

    # eval loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    print(loss.item())

4.773728847503662
4.717329025268555
4.752090930938721
4.745761394500732
4.749935150146484
4.687955856323242
4.764248847961426
4.6521406173706055
4.847356796264648
4.765072822570801
4.861966609954834
4.713894844055176
4.743587017059326
4.787214756011963
4.890217304229736
4.771665573120117
4.788496971130371
4.720020294189453
4.7808518409729
4.780531406402588
4.748926162719727
4.755062580108643
4.739818096160889
4.767740249633789
4.836137294769287
4.769327640533447
4.730599403381348
4.608950138092041
4.658009052276611
4.706156253814697
4.67409086227417
4.744751930236816
4.764608383178711
4.753079891204834
4.777052879333496
4.726086616516113
4.663741588592529
4.662285804748535
4.771123886108398
4.677136421203613
4.663066864013672
4.7853007316589355
4.643113136291504
4.717190742492676
4.691463947296143
4.647490978240967
4.676192760467529
4.690550804138184
4.696704387664795
4.730293273925781
4.725594997406006
4.598396301269531
4.8454508781433105
4.580946922302246
4.748536109924316
4.71146297

In [58]:
batch_size = 32
for steps in range(10000):

    # sample a batch of data
    xb, yb = get_batch('train')

    # eval loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.387174129486084


In [61]:
idxs = torch.zeros((1, 1), dtype=torch.long) # kickoff the generation, using 0's as the starting point for generation
print(decode(m.generate(idxs, max_new_tokens=500)[0].tolist()))


Fowigs:
LAnded therdstZMyoon Wisemand shorot bed he iveem?
SVINe h amad.
Tabe esemonerlarthardr o pr pis haire merd ror,
BORDY geronds trorldghe sh wamalandangl at, miscous d s
BEDre te bullaret.
S:

ARI e
LL:
By l berewhithefowe
Fo ts;
M3he's ad havetofaprears om le!

s ru mere pthofu:

MINoulear, ulis brell a trunoust.
Shtind:
Mad,
Bu IAThe.
Tr toss m tin,byre d, I o s Whrn out:
An:
AP ppe, my.
n! orese s anowfowk.
NERURit y de.
HULAndee weriehidistoturu be:
FI it oshotomexom beasct ruk'd, 'do


## Towards attention

In [62]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 32 # how many independent sequences will we process in parallel?
context_length = 8 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
# ------------

torch.manual_seed(1337)

In [63]:
# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('shake.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [64]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)

# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

In [65]:
# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [66]:
# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - context_length, (batch_size,))
    x = torch.stack([data[i:i+context_length] for i in ix])
    y = torch.stack([data[i+1:i+context_length+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [67]:
# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [68]:
model = BigramLanguageModel(vocab_size)
m = model.to(device)

In [69]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

In [70]:
for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

step 0: train loss 4.7305, val loss 4.7241
step 300: train loss 2.8110, val loss 2.8249
step 600: train loss 2.5434, val loss 2.5682
step 900: train loss 2.4932, val loss 2.5088
step 1200: train loss 2.4863, val loss 2.5035
step 1500: train loss 2.4665, val loss 2.4921
step 1800: train loss 2.4683, val loss 2.4936
step 2100: train loss 2.4696, val loss 2.4846
step 2400: train loss 2.4638, val loss 2.4879
step 2700: train loss 2.4738, val loss 2.4911


In [71]:
# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))




CEThik brid owindakis b, bth

HAPet bobe d e.
S:
O:3 my d?
LUCous:
Wanthar u qur, t.
War dXENDoate awice my.

Hastarom oroup
Yowhthetof isth ble mil ndill, ath iree sengmin lat Heriliovets, and Win nghir.
Swanousel lind me l.
HAshe ce hiry:
Supr aisspllw y.
Hentofu n Boopetelaves
MPOLI s, d mothakleo Windo whth eisbyo the m dourive we higend t so mower; te

AN ad nterupt f s ar igr t m:

Thin maleronth,
Mad
RD:

WISo myrangoube!
KENob&y, wardsal thes ghesthinin couk ay aney IOUSts I&fr y ce.
J
